---
- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/packages.yml
    - include: tasks/vscode.yml
    - include: tasks/extensions.yml
    - include: tasks/gnome.yml
    - include: tasks/zsh.yml
    - include: tasks/gchrome.yml
    

      