---
- name: Install Neovim and dotfile configuration
  hosts: localhost
  become_user: "{{ username }}"
  tasks:
    - name: install neovim
      become: True
      become_user: root
      package: name={{ item }}
      with_items:
        - neovim

    - name: Ensure ~/src-hub/github.com/flrnprz is present
      file: path=/home/{{ username }}/src-hub/github.com/flrnprz
            state=directory

    - name: Clone Dotfiles repository
      git: repo=https://github.com/flrnprz/dotfiles.git
           dest=/home/{{ username }}/src-hub/github.com/flrnprz/dotfiles
           update=no

    - name: Create a symlink to ~/.config/nvim/init.vim
      file: path=/home/{{ username }}/.config/nvim/init.vim
            src=/home/{{ username }}/src-hub/github.com/flrnprz/dotfiles/nvim/init.vim
            force=yes
            state=link
