---
- name: Install Some packages
  hosts: localhost
  tasks:
    - name: upgrade all packages
      become: True
      become_user: root
      package:
        name: "*"
        force_apt_get: True
        state: latest

    - name: install packages
      become: True
      package: name={{ item }}
               state=present
      with_items:
        - ack
        - autoconf
        - automake
        - bison
        - bzip2
        - curl
        - git
        - htop
        - libtool
        - make
        - tmux
        - tree
        - vim
        - copyq
        - fonts-firacode
        - git-core
        - powerline
        - zsh
