---
- name: Set Up zsh
  hosts: localhost
  become_user: "{{ username }}"
  tasks:
    - name: install zsh and prezto
      become: True
      become_user: root
      package: name={{ item }}
      with_items:
        - git-core
        - powerline
        - zsh

    - name: ensure the ~/src-hub directory is present
      file: path=/home/{{ username }}/src-hub
            state=directory

    - name: clone prezto 
      git: repo=https://github.com/sorin-ionescu/prezto.git
           dest=/home/{{ username }}/src-hub/prezto
           recursive=yes
           update=no

    - name: create symlink to prezto
      file: path=/home/{{ username }}/.zprezto
            src=/home/{{ username }}/src-hub/prezto
            state=link

    - name: check if .zshrc exists
      stat: path=/home/{{ username }}/.zshrc
      register: zshrc

    - name: back up existing .zshrc file if it exists
      when: zshrc.stat.exists
      copy: src=/home/{{ username }}/.zshrc
            dest=/home/{{ username }}/.zshrc-orig
  
    - name: Run some shell commands to config prezto
      shell: |
        setopt EXTENDED_GLOB
        for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
          ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
        done
        exit 0
      args:
        executable: /bin/zsh
  
    - name: change user shell to zsh
      become: yes
      become_user: root
      command: chsh -s /bin/zsh "{{ username }}"
