---
  - name: install extensions
    hosts: localhost
    become: True
    become_user: "{{ username }}"
    tasks:
    - name: Execute cmdline code --install-extension 
      command: code --install-extension "{{ item }}"
      with_items:
        "{{ vscode_extensions }}"
      skip_missing: yes
      register: vscode_result
      changed_when: "'already installed' not in vscode_result.stdout"