---
- name: Install Some packages
  hosts: localhost
  tasks:
    - name: upgrade all packages
      package:
        name: "*"
        force_apt_get: True
        state: latest

    - name: install packages
      package: name={{ item }}
               state=present
      with_items:
        - ack
        - autoconf
        - automake
        - bison
        - bzip2
        - chrome-gnome-shell
        - curl
        - dep
        - gcc-c++
        - git
        - htop
        - libtool
        - make
        - tmux
        - tree
        - util-linux-user
        - vim
        - copyq
        - fonts-firacore
        - git-core
        - powerline
        - zsh
