- name: Install Visual Studio Code
  hosts: localhost
  tasks:
    - name: set up vscode repo
      apt_repository:
        repo="deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" state=present filename=vscode
        update_cache=yes

    - name: upgrade all packages
      package:
        name: "*"
        force_apt_get: True
        state: latest

    - name: install vs code
      apt:
        name: code
        state: present
        
    - name: Copy User settings.json
      become: True
      become_user: "{{ username }}"
      copy: 
        src=settings.json
        dest=/home/{{ username }}/.config/Code/User/
        force=yes
      
    - name: Install VS Code extensions
      become: True
      become_user: "{{ username }}"
       
      command: code --install-extension "{{ item }}"
      with_items:
        "{{ vscode_extensions }}"
      register: vscode_result
      changed_when: "'already installed' not in vscode_result.stdout"

